# Generated by Django 2.1.7 on 2019-12-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20191222_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
